### ISSUE TITLE
Nest_Refresh

### ISSUE THREAD

**Issue by philipmhoy** [dbecknel/appdaemon#1]
What does nest_refresh referencing with the new API interface?

**Comment by dbecknel** [comment]
nest_refresh is the refresh token that Google issue once you authorize the client_id.

See "Get an Access Token" here:

https://developers.google.com/nest/device-access/authorize

**Comment by philipmhoy** [comment]
Figured it out, I needed to delete everything and try again a number to times to hit all the points as described in the procedure apparently... a big stopper for me was the formatting in the command line. Eventually got it right.
