### ISSUE TITLE
Automation overrides scheduling in place through nest app

### ISSUE THREAD

**Issue by keithjeb** [dbecknel/appdaemon#2]
Have you had any issues with automation overriding the scheduling in place through the nest app? for the moment I've disabled this (although it appears to be fully functional) as I'd rather retain a wife friendly version of the interface for scheduling.

Would you be open to PRs addressing it if I can find the relevant bit of the API?

**Comment by dbecknel** [comment]
Always open to improvements if you find, though not sure I am following on first question.

**Comment by dbecknel** [comment]
Use the main integration.  I think you are referring to the NEST schedule in the app changes the set points.  Effectively NEST has some automation running and HASS has some automation running.  I would delete the NEST schedules.
